version: "3"
services:
  web-app:
    container_name: cusg-client-web 
    image: critical-usg-client-web:${CUSG_VERSION:-latest}
    restart: always
    build:
      context: .
      args:
        CUSG_QUASAR_CONF_FILE: "${CUSG_QUASAR_CONF_FILE:-quasar.conf.prod.js}"
    ports:
      - ${CUSG_PORT-9002}:80 
